#!/bin/bash
# Quick Reference - Vestor Conversation Tests
# This file shows common commands

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                 VESTOR CONVERSATION TEST QUICK REFERENCE                   ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 RUNNING TESTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  All scenarios:          python3 tests/run_scenarios.py"
echo "  Quick tests only:       python3 tests/run_scenarios.py --quick"
echo "  Specific tags:          python3 tests/run_scenarios.py --tags beginner"
echo "  Multiple tags:          python3 tests/run_scenarios.py --tags crypto stocks"
echo "  List scenarios:         python3 tests/run_scenarios.py --list"
echo "  Smoke test (fastest):   python3 tests/quick_conversation_test.py"
echo ""

echo "✏️  CREATING NEW SCENARIOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Copy template:       cp tests/conversation_scenarios/TEMPLATE.py \\"
echo "                             tests/conversation_scenarios/my_test.py"
echo "  2. Edit the file and add your conversation"
echo "  3. Run it:              python3 tests/run_scenarios.py"
echo "     (It's auto-discovered!)"
echo ""

echo "🏷️  AVAILABLE TAGS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  beginner       - For new investors"
echo "  advanced       - For experienced traders"
echo "  stocks         - Stock-related tests"
echo "  crypto         - Cryptocurrency tests"
echo "  technical      - Technical analysis"
echo "  educational    - Educational content"
echo "  quick/smoke    - Fast validation tests"
echo "  edge-case      - Edge cases and robustness"
echo ""

echo "📁 FILE STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  tests/"
echo "  ├── conversation_scenarios/      ← Add your scenarios here!"
echo "  │   ├── base.py                  (Framework code)"
echo "  │   ├── TEMPLATE.py              (Copy this for new tests)"
echo "  │   ├── beginner_first_steps.py  (Example)"
echo "  │   └── your_scenario.py         (Your new test)"
echo "  ├── run_scenarios.py             (Main runner)"
echo "  ├── quick_conversation_test.py   (Quick smoke test)"
echo "  └── README_SCENARIOS.md          (Full documentation)"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Server not running?      python3 app.py"
echo "  Timeout errors?          Increase wait_seconds in session.say()"
echo "  Import errors?           pip install requests"
echo "  Can't find scenario?     Check class inherits from ConversationScenario"
echo ""

echo "💡 TIPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Run quick test first:  python3 tests/quick_conversation_test.py"
echo "  • Use tags to organize:  tags=['beginner', 'stocks']"
echo "  • Check responses:       session.check_response(...)"
echo "  • Real conversations:    Mimic how users actually talk"
echo "  • Auto-discovery:        Just add file, it runs automatically!"
echo ""

echo "📖 FULL DOCS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Read: tests/README_SCENARIOS.md"
echo ""
echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                           Happy Testing! 🚀                                ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
